[package]
name = "wumpus"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
csv = "1.1"
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
dirs = "5.0"  # Add this line to include the `dirs` crate
